### ISSUE TITLE
Add usage tracking

### ISSUE THREAD

**Issue by donnapep** [Automattic/WP-Job-Manager#1263]
When a user opts in to usage tracking, or a user has already opted in to usage tracking and a certain amount of time has passed, I want WP Job Manager and system info to be logged per site, so that I can make better decisions about what features to focus on improving, and to enable targeted messaging.

# Tracked Usage Data

## WP Job Manager Info

_Please note that site URL and admin email address should always be sent with each event type (`wpjm_stats_log` and `wpjm_system_log`)._

The following data should be logged under the `wpjm_stats_log` event.

### Employers
- [x] Total number of users with the _Employer_ role

### Jobs
- [x] Total number of expired jobs
- [x] Total number of preview jobs
- [x] Total number of pending jobs
- [x] Total number of pending payment jobs
- [x] Total number of published jobs

Total number of published or expired jobs that have:
  - [x] A company logo
  - [x] One or more job types selected

#### Job Data
Total number of published or expired jobs that have a non-empty (i.e. not whitespace or `null` etc.) value for:
  - [x] Location
  - [x] Application Email or URL
  - [x] Company Name
  - [x] Company Website
  - [x] Company Tagline
  - [x] Company Twitter
  - [x] Company Video
  - [x] Listing Expiry Date

Total number of published or expired jobs that have the following settings checked:
  - [x] Position Filled
  - [x] Featured Listing

Total number of published or expired jobs that:
- [x] Have been posted by a guest user

### Job Types
- [x] Total number of job types
- [x] Total number of job types that have a non-empty description
- [x] Total number of job types that have _Employment Type_ set

Total number of published or expired jobs of each type (if they exist):
  - [x] Freelance
  - [x] Full Time
  - [x] Internship
  - [x] Part Time
  - [x] Temporary

### Job Categories
- [x] Total number of job categories
- [x] Total number of job categories that have a non-empty description

You'll need to check the _Categories_ box in _Settings_ > _Job Listings_ in order to see these.

## System Info
System info should be logged under the `wpjm_system_log` event.
- [x] List of activated plugins and their versions, including WPJM
- [x] Active theme and version
- [x] WordPress version
- [x] PHP version 
- [x] Locale / language
- [x] Multisite

# How is Data Collected?
Tracking data is sent automatically once a user opts in, and then once every 2 weeks for as long as the option is enabled.

## Opt-in Setting
A new checkbox setting (default unchecked) is added to the bottom of the _General_ settings page:
- Label: Enable usage tracking
- Text: Help us make WP Job Manager better by allowing us to collect [usage tracking data](https://wpjobmanager.com/document/what-data-does-wpjm-track). No sensitive information is collected.

As well, a dismissible notice will be displayed when WPJM is updated (but only if the notice hasn't already been dismissed), that prompts the user to opt-in to usage tracking. If the user dismisses the notice or clicks either of the buttons, then the notice shouldn't appear again in the WordPress admin:

![screen shot 2018-01-08 at 8 24 33 am](https://user-images.githubusercontent.com/1190420/34672694-781cec62-f44d-11e7-81b8-f1cf1688d10c.jpg)

## Wizard
New users who are installing the plugin for the first time will be prompted to enable usage tracking in the first step of the wizard:

![screen shot 2018-01-08 at 8 21 06 am](https://user-images.githubusercontent.com/1190420/34672565-ed7505b8-f44c-11e7-8668-4ff25e54c3c0.jpg)

**Comment by wpfan2099** [comment]
good day - this is very very important! Many many thanks for bringing up this issue to us. Let us work on this - it is needed and wanted by many of us.!!!!! 

Again Thanks for your hard work!!

**Comment by donnapep** [comment]
@wpfan2099 To clarify, this is not data that will be available to plugin owners in the WordPress admin. It is strictly data that we plan to use to determine which features are used most often by our users so that we can make the right decisions on what areas of the plugin to focus on. Thx.

**Comment by alexsanford** [comment]
@donnapep Re: job expiry - this is [set automatically](https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-post-types.php#L574) and should be non-empty for all job listings. So it should always match the number of jobs. Do you want to track it anyway?

**Comment by jom** [comment]
@alexsanford If they have the `Listing Duration` setting blank the expiration is not automatically set. I think folks that use WPJM for single company job listing boards often will clear that setting.

Although the setting has a note about this, the code isn't explicit:
https://github.com/Automattic/WP-Job-Manager/blob/6b6eeb71ebf29372bc38444cb70c880c9c6aff0b/wp-job-manager-functions.php#L1312-L1320
