### ISSUE TITLE
Integrate promote button on Job Listing

### ISSUE THREAD

**Issue by renatho** [Automattic/WP-Job-Manager#2439]
- Display a promote button when the job is not promoted.
- On click, this should display a [modal](https://github.com/Automattic/WP-Job-Manager/issues/2438) with more details and then redirect to wpjobmanager.com authenticated as the site.
    - This should also send the job reference somehow to be used to create the job in JobTarget. I imagine a link to the WP core endpoint with the job details.
    - If [authentication](https://github.com/Automattic/wpjobmanager.com/issues/301) is not implemented yet, extract this part to a separate issue.
- Restrict this feature with a capability.

### Success Criteria

- [ ] ~Only users with a given capability related to promoted jobs can see the button in the Job Listings.~ (extracted to #2494)
- [x] The [authentication](https://github.com/Automattic/WP-Job-Manager/issues/2438) code also only works for users with the capability.
- [x] The click on the promote button navigates to wpjobmanager.com, sending all [parameters needed for authentication](https://github.com/Automattic/WP-Job-Manager/issues/2438).
- [x] It also sends the site lang, so we are able to translate the form and JobTarget page in the future.
