### ISSUE TITLE
Select Category  filter does not filtering via ajax 

### ISSUE THREAD

**Issue by abirdhaka7** [Automattic/WP-Job-Manager#2647]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 
- WP Job Manager Version:
- PHP Version: 
- Other important details:

```[tasklist]
### Tasks
```

**Comment by thedebian** [comment]
Hi, could you please follow the steps outlined in the issue message in order to understand the problem you're facing ?
In general, please fill out this step ***before*** clicking on "Submit new issue".
Thanks.

Edit: Closing for now, feel free to reopen or create a new issue by following the instructions
